### ISSUE TITLE
SVG injector not updating on svg file add or change

### ISSUE THREAD

**Issue by RFerber** [chrisathook/display-standard-previewer#10]
When making changes in the svg file or when adding new svgs to the html the update runs but no changes are made in the previewer until you kill it and run "watch" again

**Comment by chrisathook** [comment]
can you describe in more detail what you are doing? are you dropping new .svg files into /_svgs or editing the html in some way?

**Comment by RFerber** [comment]
When adding a new svg file to "_svgs" folder after "display-standard-previewer watch" has been run, the unit reloads but does not show the new svg.

This also occurs when making changes like switching a color value inside the svg files that have already been added. The unit will reload but changes wont be reflected.

Both issues can be solved by re running "display-standard-previewer watch"

**Comment by chrisathook** [comment]
I think this is fixed. If you reinstall and try again it should work.
