### ISSUE TITLE
Possibility of adding unique class names to inline SVGs to avoid conflicts

### ISSUE THREAD

**Issue by craigthings** [chrisathook/display-standard-previewer#11]
Currently, if two SVGs are compiled inline with the same class names, it can cause visual errors. Illustrator uses classes like st0, st1, etc. Maybe adding a unique string to the class names could solve the issue.

**Comment by hookmark** [comment]
I like the idea of a test better. That would ensure animators will be responsible for naming things properly, while allowing them flexibility for animation targeting.

**Comment by chrisathook** [comment]
Mark, can you send me a few svgs to test with. the more complex the better

**Comment by chrisathook** [comment]
added test
